#!/bin/bash

command=$*

job_command=`echo $command | awk 'BEGIN { FS="-c" } { print $2 }'`
stem_command=`echo hound $command | awk 'BEGIN { FS="-c" } { print $1 }'`

num_gpus=1
if [[ $stem_command == *"-g "* ]]; then
  num_gpus=`echo $stem_command | awk '{ sub(/.*-g /, ""); sub(/ .*/, ""); print }'`
fi

env=uv_field
if [[ $stem_command == *"--env "* ]]; then
  env=`echo $stem_command | awk '{ sub(/.*--env /, ""); sub(/ .*/, ""); print }'`
fi

job_name=Default
if [[ $stem_command == *"-n "* ]]; then
  job_name=`echo $stem_command | awk '{ sub(/.*-n /, ""); sub(/ .*/, ""); print }'`
fi

time=24
if [[ $stem_command == *"-t "* ]]; then
  time=`echo $stem_command | awk '{ sub(/.*-t /, ""); sub(/ .*/, ""); print }'`
fi

echo Creating a job with $num_gpus gpus...
echo Conda env: $env
echo Time: $time hours
echo Job command: $job_command

eval "echo \"$(cat ~/.config/hound/setup.sh)\"" > ~/tmp/slurm_script.sh
echo $job_command >> ~/tmp/slurm_script.sh
sbatch ~/tmp/slurm_script.sh
